######################################################################
##
## Filename: pwm_tb.udo
## Created on: Sat Mar 16 23:34:56 Hora oficial do Brasil 2024
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
